### ISSUE TITLE
数据怎么保存

### ISSUE THREAD

**Issue by daniel-style** [HondryTravis/xs-docs#19]
请问数据怎么和后台交互 ？还是只能在浏览器导入操作，然后导出

**Comment by hondrytravis** [comment]
可以通过 xs.getData 方法获得数据保存至后台。导入数据尽量使用 SheetJs 在前端转换，或者在后台将数据格式转好。如果有文档方面的问题可以查看 https://github.com/HondryTravis/xs-docs，如果还是不太了解，可以参考 README.md 中留下的群连接，加群讨论
