### ISSUE TITLE
开发者你好，我想请问一下，该插件是否支持excel中插入图片并导出？

### ISSUE THREAD

**Issue by Fantastic-Chen** [HondryTravis/xs-docs#2]
因为我这里有一个需求是需要导出的excel携带有图片，但是我使用其余插件的时候，导出的是浮动图片，图片需要读取线上的图片文件才可以显示，请问一下您这里有没有支持这样的功能。

**Comment by hondrytravis** [comment]
目前还暂未支持，后续可能会更新，更加大家使用情况，现在建议自己做自定义开发，源码不难的
