### ISSUE TITLE
修改Toolbar 上面功能选项 

### ISSUE THREAD

**Issue by wujianglong** [HondryTravis/xs-docs#7]
你好作者
 我想要的功能比较简单 能合并单元格
1. 所以我并不需要全部的Toolbar上的功能 需要隐藏不用的
2. 或者我能够右键 里面就可以合并单元格
以上该怎么操作呢

**Comment by hondrytravis** [comment]
需要修改源码，找到对应的toolbar功能创建class的地方，在构造函数里让自己hide就好了

**Comment by hondrytravis** [comment]
可以参考文档 https://github.com/HondryTravis/xs-docs 进行研究，有问题可以加群讨论，在 README.md 里
