### ISSUE TITLE
右下角统计

### ISSUE THREAD

**Issue by xiaoze-smirk** [HondryTravis/xs-docs#9]
你好，一个问题，打印这边有两个奇怪的外方框
![image](https://user-images.githubusercontent.com/25415210/93456992-0614ad00-f911-11ea-88fd-606cd65812f9.png)

接着两个建议(只是我个人想法，莫怪):
1、右下角统计可否方便列入今后的开发中。
2、点击表格可否边框高亮并且提示信息，比如名字等等，这个功能可否列入今后的开发中。

**Comment by hondrytravis** [comment]
进入官方群咨询看看980597168
